---
kind: pipeline
type: docker
name: xiaomi_ax3200_openwrt

trigger:
  event:
    exclude:
      - pull_request

steps:
  # - name: lint
  #   image: alpine:3.14
  #   pull: always
  #   commands:
  #     - apk add --no-cache shellcheck py-pip python3 bash
  #     - pip3 install yamllint
  #     - yamllint .
  #     - shellcheck ./*.sh

  - name: build
    image: debian:buster
    pull: always
    volumes:
      - name: build-artifacts
        path: /tmp/artifacts
    commands:
      - /bin/bash -c "set -o pipefail; build_image/build_image_in_docker.sh 2>&1 | tee /tmp/artifacts/build.log"

  - name: publish-github
    image: plugins/github-release
    volumes:
      - name: build-artifacts
        path: /tmp/artifacts
    settings:
      api_key:
        from_secret: github_token
      files: /tmp/artifacts/*
      prerelease: true
    when:
      event: tag

volumes:
  - name: build-artifacts
    temp: {}
